name: theme_dev
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - importlib_resources
  - click
  - sphinx>3.1
  - jupyter
  - jupytext
  - pip
  - libsass
  - ghp-import
#conda-lock -f environment.yml -p linux-64




